name: counter_app_with_selective_rebuild
description: Counter demo app with selective rebuild implemented with 'reduced' API and 'reduced_setstate' implementation as an example of how to use the 'reduced' package.
publish_to: 'none' 
version: 0.4.1+7

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
#  reduced: 0.4.1
  reduced: 
    git:
      url: https://github.com/partmaster/reduced.git
      ref: v0.4.1-beta.4
  reduced_streambuilder: 
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
